# import colors
general.import = [
  "~/.config/alacritty/gruvbox-material-soft-dark.toml"
]

[font]
size = 12.0

[font.normal]
family = "CommitMono Nerd Font Mono"
style = "Normal"

[font.bold]
family = "CommitMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CommitMono Nerd Font Mono"
style = "Bold Italic"

[window]
padding = { x = 10, y = 10 }

[cursor]
style = { shape = "Beam", blinking = "On" }
